### ISSUE TITLE
Where is the latest docker-compose.yml file?

### ISSUE THREAD

**Issue by hiroyuki-sato** [RCOSDP/RDM-osf.io#509]
Hello, team.

## Overview

I want to run the RDM server for test connecting storage. (I don't develop this project)

## Questions.

* What branch should I use?
* Where is the latest `docker-compose.yml` file?

##  Problem

When I try `docker-compose up requirements mfr_requirements wb_requirements`

It didn't work with many errors. (please see the attached file)
[docker-compose.txt](https://github.com/user-attachments/files/16284331/docker-compose.txt)

For example, It seems that the Python version of `docker-compose` file and `quay.io/centerforopenscience/mfr:develop` did not match.

| File/Image   | Python |
|-------------|--------|
|  quay.io/centerforopenscience/mfr:develop | python 3.6 |
|  mfr_requirements  docker-compose.yml | python 3.5 |

https://github.com/RCOSDP/RDM-osf.io/blob/develop/docker-compose.yml

Could someone tell me how to use this project?

```
docker run -it quay.io/centerforopenscience/mfr:develop /bin/bash
root@ab43e171a183:/code# python --version
Python 3.6.15
```

```yaml
  #########################
  # Modular File Renderer #
  #########################

  mfr_requirements:
    image: quay.io/centerforopenscience/mfr:develop
    command:
      - /bin/bash
      - -c
      - invoke install --develop &&
        (python -m compileall /usr/local/lib/python3.5 || true) &&
        rm -Rf /python3.5/* &&
        cp -Rf -p /usr/local/lib/python3.5 /
    restart: 'no'
    volumes:
      - mfr_requirements_vol:/python3.5
      - mfr_requirements_local_bin_vol:/usr/local/bin
```

## environment

* docker: Docker version 27.0.3, build 7d4bcd8
* Docker Compose version v2.29.0

* RDM-osf.io: bd5b4db5a262bdde900cd4813e77a3d37d31c30a / and `release/24.07.10`
* Ubuntu 22.04

```
docker image ls
REPOSITORY                         TAG       IMAGE ID       CREATED        SIZE
quay.io/centerforopenscience/osf   develop   b4b90a0f118e   5 days ago     1.3GB
quay.io/centerforopenscience/wb    develop   2958f43a84dc   2 weeks ago    617MB
quay.io/centerforopenscience/mfr   develop   bf08566d8364   6 months ago   3.01GB
```
